export const AboutStyle = {
  section:      'bg-zinc-950 py-24 px-6',
  inner:        'max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-16 items-center',
  leftCol:      'flex flex-col',
  sectionLabel: 'text-xs text-amber-400 font-medium tracking-widest uppercase mb-4 animate-fade-up delay-1',
  title:        'text-4xl md:text-5xl font-bold text-white font-display mb-6 leading-tight animate-fade-up delay-2',
  titleAccent:  'text-amber-400',
  body:         'text-zinc-400 text-base leading-relaxed mb-4 animate-fade-up delay-3',
  divider:      'w-12 h-px bg-amber-400 mt-8 animate-fade-up delay-3',
  rightCol:     'flex flex-col gap-4 animate-fade-up delay-4',
  featureItem:  'flex items-start gap-4 bg-zinc-900 border border-zinc-800 p-5 hover:border-amber-400/40 transition-colors duration-300',
  featureBullet:'text-amber-400 text-lg mt-0.5 select-none shrink-0',
  featureTitle: 'text-white text-sm font-semibold uppercase tracking-wide mb-1',
  featureDesc:  'text-zinc-500 text-sm leading-relaxed',
}
