export const BookingStyle = {
  backdrop:     'fixed inset-0 z-[100] flex items-center justify-center px-6 py-10 backdrop-blur-sm bg-black/70',
  card:         'relative w-full max-w-lg bg-white/5 backdrop-blur-md border border-white/10 p-8 shadow-2xl shadow-black/60',
  closeBtn:     'absolute top-4 right-4 text-zinc-500 hover:text-amber-400 text-lg transition-colors duration-200 cursor-pointer',
  label:        'text-amber-400 text-xs tracking-widest font-mono uppercase mb-2 text-center',
  title:        'text-transparent bg-clip-text bg-gradient-to-r from-white to-amber-200 text-4xl font-extrabold uppercase tracking-wide text-center mb-2 font-display drop-shadow-lg',
  divider:      'w-16 h-px bg-amber-400 mx-auto mb-4 shadow-[0_0_8px_rgba(201,168,76,0.5)]',
  subtitle:     'text-zinc-400 text-sm text-center mb-8 leading-relaxed',
  form:         'flex flex-col gap-5',
  inputGroup:   'flex flex-col gap-1.5',
  inputLabel:   'text-zinc-400 text-xs font-semibold tracking-widest uppercase',
  input:        'w-full bg-white/5 border border-white/10 px-4 py-3 text-white text-sm placeholder:text-zinc-600 focus:outline-none focus:border-amber-400/70 focus:ring-2 focus:ring-amber-400/20 focus:bg-white/10 transition-all duration-300',
  select:       'w-full bg-zinc-900 border border-white/10 px-4 py-3 text-white text-sm focus:outline-none focus:border-amber-400/70 focus:ring-2 focus:ring-amber-400/20 transition-all duration-300 cursor-pointer',
  row:          'grid grid-cols-2 gap-4',
  button:       'w-full mt-2 py-3 bg-amber-400 text-zinc-950 text-sm font-bold tracking-widest uppercase shadow-lg shadow-amber-900/30 transition-all duration-300 hover:bg-amber-300 hover:-translate-y-1 hover:shadow-xl hover:shadow-amber-500/30 active:scale-95 cursor-pointer',
  buttonOutline:'w-full mt-1 py-3 bg-transparent border border-white/20 text-zinc-400 text-sm font-bold tracking-widest uppercase transition-all duration-300 hover:border-amber-400/60 hover:text-white hover:-translate-y-1 active:scale-95 cursor-pointer',
  successWrap:  'flex flex-col items-center gap-4 py-6',
  successIcon:  'text-amber-400 text-4xl',
  successTitle: 'text-white text-xl font-bold font-display tracking-wide text-center',
  successText:  'text-zinc-400 text-sm text-center leading-relaxed',
  errorMsg:     'text-red-400 text-xs mt-1',
}
