export const LocationStyle = {
  section:       'bg-textured py-24 px-6',
  inner:         'max-w-7xl mx-auto',
  header:        'mb-12',
  sectionLabel:  'text-xs text-amber-400 font-medium tracking-widest uppercase mb-4 animate-fade-up delay-1',
  title:         'text-4xl md:text-5xl font-bold text-white font-display animate-fade-up delay-2',
  grid:          'grid grid-cols-1 md:grid-cols-2 gap-10 items-start animate-fade-up delay-3',
  mapCol:        'flex flex-col gap-5',
  mapFrame:      'w-full h-72 md:h-96 border border-zinc-800 grayscale',
  addressBox:    'flex flex-col gap-3',
  addressLabel:  'text-xs text-amber-400 font-medium tracking-widest uppercase',
  addressText:   'text-zinc-300 text-sm leading-relaxed',
  mapsBtn:       'inline-flex items-center gap-2 px-5 py-2.5 border border-amber-400 text-amber-400 text-xs font-semibold uppercase tracking-widest hover:bg-amber-400 hover:text-zinc-950 transition-all duration-300 w-fit',
  hoursCol:      'flex flex-col gap-4',
  hoursTitle:    'text-xs text-amber-400 font-medium tracking-widest uppercase mb-2',
  hoursTable:    'w-full border-collapse',
  hoursRow:      'border-b border-zinc-800',
  hoursDay:      'text-zinc-400 text-sm py-3 pr-6',
  hoursTime:     'text-white text-sm py-3 text-right font-medium',
  hoursClosed:   'text-red-500 text-sm py-3 text-right font-medium',
  hoursNote:     'text-zinc-600 text-xs mt-4 leading-relaxed',
}
