export const TestimonialsStyle = {
  section:      'bg-zinc-950 py-24 px-6',
  inner:        'max-w-6xl mx-auto',
  header:       'mb-12',
  sectionLabel: 'text-xs text-amber-400 font-medium tracking-widest uppercase mb-4 animate-fade-up delay-1',
  title:        'text-4xl md:text-5xl font-bold text-white font-display animate-fade-up delay-2',
  grid:         'grid grid-cols-1 md:grid-cols-3 gap-6 animate-fade-up delay-3',
  card:         'bg-zinc-900 border border-zinc-800 p-6 relative flex flex-col',
  quote:        'text-6xl text-amber-400 font-display leading-none mb-2 select-none',
  text:         'text-zinc-300 text-sm leading-relaxed mb-6 flex-1',
  footer:       'flex items-center gap-3 border-t border-zinc-800 pt-4',
  avatar:       'w-9 h-9 rounded-full bg-amber-400/20 border border-amber-400/30 flex items-center justify-center text-amber-400 text-xs font-bold uppercase shrink-0',
  author:       'text-amber-400 text-xs font-semibold uppercase tracking-widest',
  stars:        'text-amber-400 text-xs tracking-widest',
}
