export const SubscribeStyle = {
  section:      'bg-zinc-950 py-24 px-6',
  inner:        'max-w-xl mx-auto text-center',
  sectionLabel: 'text-xs text-amber-400 font-medium tracking-widest uppercase mb-4 animate-fade-up delay-1',
  title:        'text-4xl md:text-5xl font-bold text-white font-display mb-4 animate-fade-up delay-2',
  subtitle:     'text-zinc-400 text-base leading-relaxed mb-10 animate-fade-up delay-3',
  form:         'flex flex-col gap-4 text-left animate-fade-up delay-4',
  inputWrapper: 'flex flex-col gap-1',
  label:        'text-zinc-500 text-xs uppercase tracking-widest',
  input:        'bg-zinc-900 border border-zinc-800 text-white text-sm px-4 py-3 outline-none focus:border-amber-400 transition-colors duration-300 placeholder:text-zinc-700',
  checkboxRow:  'flex items-start gap-3',
  checkbox:     'mt-0.5 w-4 h-4 accent-amber-400 shrink-0 cursor-pointer',
  checkboxLabel:'text-zinc-500 text-xs leading-relaxed',
  checkboxLink: 'text-amber-400 hover:underline cursor-pointer',
  submitBtn:    'w-full py-4 bg-amber-400 text-zinc-950 text-sm font-semibold uppercase tracking-widest hover:bg-amber-300 transition-colors duration-300 cursor-pointer mt-2',
  footerNote:   'text-zinc-600 text-xs mt-6 leading-relaxed text-center',
  successMsg:   'w-full py-4 bg-zinc-900 border border-amber-400/40 text-amber-400 text-sm font-semibold uppercase tracking-widest text-center mt-2',
  errorMsg:     'text-red-400 text-xs mt-1',
}
